### PR TITLE
Fix bug where docs weren't annotating

### LINKED ISSUE #206: text not being annotated
English text which should be getting annotated is not occurring. We need to figure out why.

Source dataset: https://s3.console.aws.amazon.com/s3/object/temp-aria-mapping?region=eu-west-2&prefix=patents_for_annotation.json

### PR DESCRIPTION
**Pull request by doogyb**
The bulk API for ElasticSearch wasn't waiting for the shards to refresh, resulting in a significant portion of documents not being annotated at all. By using the refresh=wait_for query paramater, we ensure that the docs are both uploaded and ready to be annoated before launching the service.

Also:
- make the "simple" S3 output format the default.

fixes #206

### CODE REVIEW

File: src/node_modules/dbpedia/spotlight.mjs [hunk 1]
```diff
@@ -421,7 +426,13 @@ export const annotateIndex = async (
 		// this is likely to be too big, so separate by default size
 		const batchedUpdates = batch(flattenedUpdates, 500);
 		for await (const update_ of batchedUpdates) {
-			await bulkRequest(domain, index, update_, 'update', { error: false });
+			await bulkRequest(
+				domain,
+				index,
+				update_,
+				'update',
+				{ error: false, refresh: "wait_for" }
```
Comment (mindrones) [inline src/node_modules/dbpedia/spotlight.mjs]: minor, I'd use single quotes

**Review by mindrones — APPROVED** [review]
GTM with minor comment
