### PR TITLE
66 fix bulk update bug when no requests

### LINKED ISSUE #66: Bulk update fails when no requests are passed

### PR DESCRIPTION
**Pull request by doogyb**
fixes #66

### CODE REVIEW

File: arxlive_spotlight_annotation/src/node_modules/es/update.mjs [hunk 1]
```diff
@@ -36,7 +36,7 @@ const generateBulkUpdatePayload = index => _.pipe([
 	json => `${json}\n`
 ])
 
-/**
+/**o
```
Comment (mindrones) [inline arxlive_spotlight_annotation/src/node_modules/es/update.mjs]: typo?

File: arxlive_spotlight_annotation/src/node_modules/es/update.mjs [hunk 2]
```diff
@@ -49,6 +49,11 @@ export const bulkUpdate = async (domain, index, documents, options = {}) => {
 	const path = `${index}/_bulk`
 	const generateForIndex = generateBulkUpdatePayload(index)
 	const payload = generateForIndex(documents)
+	// if payload is empty, no docs were supplied to the function
+	// this can happene when we filter out docs that never recieved any annotations
```
Comment (mindrones) [inline arxlive_spotlight_annotation/src/node_modules/es/update.mjs]:
```suggestion
	// this can happene when we filter out docs that never received any annotations
```

File: arxlive_spotlight_annotation/src/bin/es/annotate.mjs [hunk 3]
```diff
@@ -60,7 +60,7 @@ program.option(
 )
 
 program.parse();
-const options = program.opts();
+console.log(typeof options.batchSize)
```
Comment (mindrones) [inline arxlive_spotlight_annotation/src/bin/es/annotate.mjs]: leftover I think

**Review by mindrones — APPROVED** [review]
GTM apart from some minor comments below
