### PR TITLE
Force flag allows proceed when field exists

### LINKED ISSUE #24: Allow force option to annotate when field exists in mapping
The force flag should allow annotation to proceed even when the annotation field being added already exists in the index (in the case where the user either wants to update that field or continue from a previous annotation run that failed or was interrupted).

Also, the `testAnnotationLocally` npm script should name the field `dbpedia_entities` instead of using the default computed name to clone the schema used in `arxiv_v6`. This is not possible without first solving the issue described above.

### PR DESCRIPTION
**Pull request by doogyb**
Supplying the force flag to arxlive_spotlight_annotation/src/bin/es/annotate.mjs
will now allow the script to continue, regardless of whether the
supplied field argument exists on the index's mapping or not.

This then allows the testAnnotationLocally npm script to name the
annotated field 'dbpedia_entities', which will mimic the arxiv_v6
schema so that the test index and arxiv_6 index can be queried using
the exact same request bodies.

closes #24

Also:
- cleanup arxlive_spotlight_annotation/src/bin/es/index.mjs (remove console.logs)
- cleanup arxlive_spotlight_annotation/src/node_modules/conf/mappings.mjs (remove redundant fields)
- cleanup arxlive_spotlight_annotation/src/node_modules/es/requests.mjs (remove stale imports)
- cleanup arxlive_spotlight_annotation/src/node_modules/es/snapshot.mjs (return request object instead of request body)

### CODE REVIEW

File: arxlive_spotlight_annotation/src/node_modules/conf/mappings.mjs [hunk 1]
```diff
@@ -1,6 +1,7 @@
 export const defaultMapping = {
 	mappings: {
 		properties: {
+			"description": "string",
```
Comment (mindrones) [inline arxlive_spotlight_annotation/src/node_modules/conf/mappings.mjs]:
```suggestion
			description: 'string',
```

**Review by mindrones — APPROVED** [review]
GTM after tackling a minor comment below
