### PR TITLE
Batch documents upon ingestion

### LINKED ISSUE #92: Batch call bulk request when using ingestion script
`ingestion.mjs` script is currently failing silently - only uploading 308 docs to the index when there should be 3019. I think this has to do with a the bulk request being too large (although this needs investigation). Either way, batching the documents when performing ingestion is a required feature if/when json documents do become very large, so creating this issue for that feature. Hopefully it will also fix the bug.

### PR DESCRIPTION
**Pull request by doogyb**
PR to add batch functionality for the ingestion script. Also adds
logging for any errors that may occur upon ingestion.

closes #92

Also
- fix import error in bulk.mjs (no import for stringify function)
- fix Commander parsing error (function comes first, default value second)

### CODE REVIEW

File: src/bin/es/annotate.mjs [hunk 1]
```diff
@@ -167,4 +168,4 @@ const main = async () => {
 	);
 };
 
-main();
+// main();
```
Comment (mindrones) [inline src/bin/es/annotate.mjs]: leftover?

File: src/bin/es/ingest.mjs [hunk 2]
```diff
@@ -2,10 +2,14 @@ import { promises as fs } from 'fs';
 
 import { Command } from 'commander';
 import * as _ from 'lamb';
+import { stringify } from '@svizzle/utils';
```
Comment (mindrones) [inline src/bin/es/ingest.mjs]: seems unused

File: src/bin/es/ingest.mjs [hunk 3]
```diff
@@ -29,6 +34,11 @@ program.option(
 program.parse();
 const options = program.opts();
 
+const logErrors = _.pipe([
+    _.filterWith(item => parseInt(item.create.status/100) !== 2),
+    _.mapWith(item => logger.error(item))
```
Comment (mindrones) [inline src/bin/es/ingest.mjs]: I think here you could use 
```suggestion
    _.mapWith(logger.error)
```

File: src/node_modules/util/string.mjs [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import * as _ from 'lamb'
+import { trim } from '@svizzle/utils'
+
+
+export const toLowerString = v => v.toString().toLowerCase()
+// tag function to dedent template literals
+export const dedent = _.pipe([
```
Comment (mindrones) [inline src/node_modules/util/string.mjs]: formatting: I'd have a single blank line between each function and between the imports block and the first function

File: src/node_modules/util/spotlight.mjs [hunk 5]
```diff
@@ -0,0 +1,5 @@
+import * as _ from 'lamb'
+
+
+export const uniquesByURI =
+	_.uniquesBy(_.getKey('URI'))
```
Comment (mindrones) [inline src/node_modules/util/spotlight.mjs]: seems unused?

File: src/node_modules/util/promises.mjs [hunk 6]
```diff
@@ -0,0 +1,18 @@
+import { getValue } from '@svizzle/utils'
+import { logger } from 'logging/logging.mjs'
+
+
+const logErrors = v => {
```
Comment (mindrones) [inline src/node_modules/util/promises.mjs]: 1) formatting, there should be a single blank line after imports

File: src/node_modules/util/commander.mjs [hunk 7]
```diff
@@ -0,0 +1,10 @@
+import { InvalidArgumentError } from 'commander'
+
+
+export const commanderParseInt = (value, _) => {
```
Comment (mindrones) [inline src/node_modules/util/commander.mjs]: formatting, see 1)

File: src/node_modules/util/array.mjs [hunk 8]
```diff
@@ -0,0 +1,13 @@
+import * as _ from 'lamb'
+import { isNotNil } from '@svizzle/utils'
+
+
+const _batch = (arr, batchSize) => {
```
Comment (mindrones) [inline src/node_modules/util/array.mjs]: see 1)

File: src/bin/es/ingest.mjs [hunk 9]
```diff
@@ -1,11 +1,13 @@
...
 import { Command } from 'commander';
-import * as _ from 'lamb';
-
+import { bulkRequest } from 'es/bulk.mjs'
 import { arxliveCopy } from 'conf/config.mjs';
 import { createIndex } from 'es/index.mjs'
-import { bulkRequest } from 'es/bulk.mjs'
+import { logger } from 'logging/logging.mjs'
+import { batch } from 'util/array.mjs'
+import { commanderParseInt } from 'util/commander.mjs'
```
Comment (mindrones) [inline src/bin/es/ingest.mjs]: 2) imports should be formatted as usual  (node, npm, local, each block separated by a single line and sorted by module name/path)

```js
import { promises as fs } from 'fs';

import { Command } from 'commander';
import * as _ from 'lamb';

import { arxliveCopy } from 'conf/config.mjs';
import { bulkRequest } from 'es/bulk.mjs';
import { createIndex } from 'es/index.mjs';
import { logger } from 'logging/logging.mjs';
import { batch } from 'util/array.mjs';
import { commanderParseInt } from 'util/commander.mjs';
```

File: src/bin/es/annotate.mjs [hunk 10]
```diff
@@ -10,7 +10,9 @@ import {
 	annotateDocument,
 } from 'dbpedia/spotlight.mjs';
 import { arxliveCopy } from 'conf/config.mjs';
-import { promisesHandler, batch, commanderParseInt } from '../../node_modules/util.mjs';
+import { promisesHandler } from 'util/promises.mjs'
+import { batch } from 'util/array.mjs'
+import { commanderParseInt } from 'util/commander.mjs'
 import { settings, defaultMapping, metaDataMapping } from 'conf/config.mjs';
```
Comment (mindrones) [inline src/bin/es/annotate.mjs]: see 2)

**Review by mindrones — CHANGES_REQUESTED** [review]
first pass, mostly formatting

File: src/bin/es/ingest.mjs [hunk 11]
```diff
@@ -3,9 +3,12 @@ import { promises as fs } from 'fs';
 import { Command } from 'commander';
 import * as _ from 'lamb';
```
Comment (mindrones) [inline src/bin/es/ingest.mjs:4]: these imports should be sorted

File: src/node_modules/util/array.mjs [hunk 12]
```diff
@@ -0,0 +1,13 @@
+import * as _ from 'lamb'
+import { isNotNil } from '@svizzle/utils'
```
Comment (mindrones) [inline src/node_modules/util/array.mjs]: these imports should be sorted

File: src/bin/es/ingest.mjs [hunk 13]
```diff
@@ -3,9 +3,12 @@ import { promises as fs } from 'fs';
...
 
+import { bulkRequest } from 'es/bulk.mjs';
 import { arxliveCopy } from 'conf/config.mjs';
-import { createIndex } from 'es/index.mjs'
-import { bulkRequest } from 'es/bulk.mjs'
+import { createIndex } from 'es/index.mjs';
```
Comment (mindrones) [inline src/bin/es/ingest.mjs]: theer imports need sorting

**Review by mindrones — APPROVED** [review]
GTM, I just left 3 formatting comments below
